version: '3'
services:

  rabbitmq:
    image: waggle/rabbitmq:nc
    env_file:
      - waggle-node.env
    ports:
      - "127.0.0.1:15672:15672"
    volumes:
      - "${WAGGLE_ETC_ROOT}:/etc/waggle:ro"
    networks:
      - waggle
    restart: always

  registration:
    image: waggle/registration
    env_file:
      - waggle-node.env
    volumes:
      - "${WAGGLE_ETC_ROOT}:/etc/waggle"
    networks:
      - waggle
    restart: on-failure

  stage-messages:
    image: waggle/stage-messages
    env_file:
      - waggle-node.env
    volumes:
      - "${WAGGLE_ETC_ROOT}:/etc/waggle:ro"
    networks:
      - waggle
    restart: always
    command: amqp://worker:worker@rabbitmq messages 0000000000000000 amqp://worker:worker@rabbitmq to-beehive
  
  shovelctl:
    image: waggle/shovelctl
    env_file:
      - waggle-node.env
    networks:
      - waggle
    command: enable

networks:
  waggle:
