version: '3'
services:

  rabbitmq:
    image: waggle/rabbitmq:nc
    env_file:
      - waggle-node.env
    volumes:
      - waggle-data:/etc/waggle
    networks:
      - waggle
    restart: always

  registration:
    image: waggle/registration
    env_file:
      - waggle-node.env
    volumes:
      - waggle-data:/etc/waggle
      - "${WAGGLE_ETC_ROOT}/register.pem:/etc/waggle/register.pem:ro"
    networks:
      - waggle
    restart: on-failure

  stage-messages:
    image: waggle/stage-messages
    env_file:
      - waggle-node.env
    volumes:
      - waggle-data:/etc/waggle
    networks:
      - waggle
    restart: always
    command: amqp://worker:worker@rabbitmq messages 0000000000000000 amqp://worker:worker@rabbitmq to-beehive
  
  shovelctl:
    image: waggle/shovelctl
    env_file:
      - waggle-node.env
    networks:
      - waggle
    command: enable
  
  playback:
    image: waggle/playback-server
    env_file:
      - waggle-node.env
    networks:
      - waggle
    volumes:
      - "./playback:/data:ro"

volumes:
  waggle-data:

networks:
  waggle:
