version: '3'
services:

  rabbitmq:
    image: waggle/rabbitmq:nc
    env_file:
      - waggle-node.env
    volumes:
      - waggle-data:/etc/waggle
    networks:
      - waggle
    restart: always

  registration:
    image: waggle/registration
    env_file:
      - waggle-node.env
    volumes:
      - waggle-data:/etc/waggle
      - ./private/register.pem:/etc/waggle/register.pem:ro
    networks:
      - waggle
    restart: on-failure

  data-sharing-service:
    image: waggle/data-sharing-service
    env_file:
      - waggle-node.env
    volumes:
      - waggle-data:/etc/waggle
    networks:
      - waggle
    restart: always
    command: amqp://worker:worker@rabbitmq

  shovelctl:
    image: waggle/shovelctl
    env_file:
      - waggle-node.env
    networks:
      - waggle
    command: enable
  
  playback:
    image: waggle/playback-server
    env_file:
      - waggle-node.env
    networks:
      - waggle
    volumes:
      - "./playback:/data:ro"

volumes:
  waggle-data:

networks:
  waggle:
