#!/bin/bash -e

# use waggle node environment
set -a
source waggle-node.env
set +a

# use docker-compose.plugins.yml if it exists
if [ -e 'docker-compose.plugins.yml' ]; then
    compose_file_args='-f docker-compose.yml -f docker-compose.plugins.yml'
else
    compose_file_args='-f docker-compose.yml'
fi

command_up() {
    docker-compose $compose_file_args up --build -d --remove-orphans

    while ! python3 utils/shovelctl.py enable; do
        sleep 3
    done
}

cleanup_files() {
    for path in $*; do
        if [ -e "$path" ]; then
            echo "Clean up $path"
            rm $path
        fi
    done
}

command_down() {
    docker-compose $compose_file_args down --remove-orphans
    cleanup_files "docker-compose.plugins.yml" \
                  "private/cacert.pem" \
                  "private/cert.pem" \
                  "private/key.pem" \
                  "private/reverse_ssh_port"
}

command_logs() {
    docker-compose $compose_file_args logs --tail 100 -f
}

command_schedule() {
    python3 utils/set-node-plugins.py $@
}

command="$1"
shift

case "$command" in
    up) command_up $@ ;;
    down) command_down $@ ;;
    logs) command_logs $@ ;;
    schedule) command_schedule $@ ;;
esac
